### ISSUE TITLE
markdown images fail on barnstar wiki page

### ISSUE THREAD

**Issue by btbonval** [jywarren/plots2#186] opened 2013-10-06 21:31 UTC
proper markdown image here:
http://www.publiclab.org/wiki/revisions/barnstars/16126

showed up fine in preview, on publish the markdown showed up literally, without interpretation.

replaced with HTML here
http://www.publiclab.org/wiki/revisions/barnstars/16127

**Comment by jywarren** [comment] 2015-02-21 02:27
#187 is closed; also I'm closing this because it's expected behavior for Markdown inside of HTML tags not to be interpreted. We could, if we like, diverge from Markdown convention.

**Closed by jywarren** 2015-02-21 02:27 UTC
Labels: bug
